CREATE TABLE Videos
(
	[Id] [uniqueidentifier] ROWGUIDCOL NOT NULL DEFAULT NEWSEQUENTIALID() UNIQUE, 
	[SerialNumber] INT IDENTITY(1,1) UNIQUE,
	[Name] NVARCHAR(MAX),
	[Stream] VARBINARY(MAX) FILESTREAM NULL
) FILESTREAM_ON [FileStreamGroup1];

